<?php
include('setting/config.php');
if(empty($_SESSION['status'])){
    header("location:".$domain."akun/masuk");
}
if($_GET['halaman']=="tambah"){
    include('view/lpj/tambah.php');
}elseif($_GET['halaman']=="edit"){
    include('view/lpj/edit.php');
}else{
    include('view/lpj/lpj.php');
}
?>