<?php
include('setting/config.php');
if(empty($_SESSION['status'])){
    header("location:".$domain."akun/masuk");
}
if($_GET['halaman']=="tambah"){
    include('view/proposal/tambah.php');
}elseif($_GET['halaman']=="edit"){
    include('view/proposal/edit.php');
}else{
    include('view/proposal/proposal.php');
}
?>